#!/bin/bash

screen -r -S PainelDTunnel -X quit
cd /
[[ -e /root/PainelDTunnel/prime ]] && {
  screen -dmS "PainelDTunnel" sh start.sh
  echo
  echo "PainelDTunnel Online (WAPI)"
  echo
  exit 0
}
touch prime
#echo "ps x | grep 'wapi' | grep -v 'grep' || cd /root/apiWa && sudo screen -dmS 'wapi' sh start.sh && cd /root" >> /etc/autostart
(crontab -l > /tmp/apiWaRes; echo "@reboot sleep 10 && pon" >> /tmp/apiWaRes; cat /tmp/apiWaRes) | crontab -
screen -dmS "PainelDTunnel" sh start.sh
echo
echo "PainelDTunnel Online (PRIME)"
echo
